@MicroServicioUsuario_HostAddress = http://localhost:5221

### Login válido
POST {{MicroServicioUsuario_HostAddress}}/api/autenticacion/login
Content-Type: application/json

{
  "usuario": "Admin",
  "contrasena": "TuPasswordAqui"
}

###

### Campos vacíos
POST {{MicroServicioUsuario_HostAddress}}/api/autenticacion/login
Content-Type: application/json

{
  "usuario": "",
  "contrasena": ""
}

###

### Credenciales incorrectas
POST {{MicroServicioUsuario_HostAddress}}/api/autenticacion/login
Content-Type: application/json

{
  "usuario": "UsuarioInexistente",
  "contrasena": "PasswordIncorrecto"
}
